### ISSUE TITLE
issue about embed.py and setup.py

### ISSUE THREAD

**Issue by robloxian34535** [kyb3r/dhooks#24]
I tried ran the embed.py
and it doesnt work at all.. Yes I did put my webhook there.
I don't know about setup.py but it failed to install or given error but it close the cmd so fast. I don't know the errors anyway

I did pip install dhooks and already installed for now...
My python version is 3.6.4
My pip version is 19.1.1

**Comment by Taaku18** [comment]
You’ll need to read the installation guide, simply a `pip install dhooks` will work. https://github.com/kyb3r/dhooks/blob/master/README.md. As for embed.py, itself is not a standalone program, it contains an object representing an embed object from discord API. Please read the README file.

**Comment by robloxian34535** [comment]
> You’ll need to read the installation guide, simply a `pip install dhooks` will work. https://github.com/kyb3r/dhooks/blob/master/README.md. As for embed.py, itself is not a standalone program, it contains an object representing an embed object from discord API. Please read the README file.

Sadly I've already installed the dhooks.

But

So I run this i'm not going to put my webhook link there too risky to give out..
from dhooks import Webhook

hook = Webhook('MYWEBHOOK')

hook.send("Hello there! I'm a webhook :open_mouth:")

and ran it with run.py

and it didnt send anything.. and it close the cmd very quicky

**Comment by robloxian34535** [comment]
@Taaku18

**Comment by Taaku18** [comment]
Could you try running the python file from cmd with the `python` command? This way the cmd window wouldn’t immediately close after the program terminated.

**Comment by robloxian34535** [comment]
Now it work.

Thanks. Do you mind delete/edit the link picture of prnt.sc on other issue?

**Comment by Taaku18** [comment]
Yeah, don’t worry, @kyb3r can delete the issues. (Intentional ping)
