### ISSUE TITLE
to Taaku18

### ISSUE THREAD

**Issue by robloxian34535** [kyb3r/dhooks#25]
https://github.com/kyb3r/dhooks/issues/24#issuecomment-511016976

I already read the READMD.

But for some reason it doesn't work at all... and doesnt send the message which i already put the full webhook link

https://prnt.sc/oeacva
already installed the dhooks

**Comment by Taaku18** [comment]
You can continue to message even if it’s closed. Opening a new issue isn’t necessary. I’ll be closing this and continue the conversation in the other issue, I’ll reopen that other issue if it’s deemed to be a bug.
