### ISSUE TITLE
No module named dhooks

### ISSUE THREAD

**Issue by IchiiSama** [kyb3r/dhooks#26]
Hi, i've installed the package twice today and python says to me that `ModuleNotFoundError: No module named 'dhooks'`, while it was working on my other computer... Can you help me ?

**Comment by StephenDaDev** [comment]
Did you use ``pip install dhooks``?

**Comment by IchiiSama** [comment]
I've done this twice like i said in the thread :/

**Comment by IchiiSama** [comment]
Oh ok, just changed the `from dhooks import WebHook` to `from dhooks import Webhook` and it worked ! (I'm closing the issue)

**Comment by IchiiSama** [comment]
oopsy, i've closed then reopened because i thought it was working but it don't work on my .py file

**Comment by kyb3r** [comment]
what is the name of the py file you are running?
