### ISSUE TITLE
 SyntaxError: unexpected character after line continuation character

### ISSUE THREAD

**Issue by dducted** [kyb3r/dhooks#30]
Hi there, I am getting the following error:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from dhooks import Webhook
  File "/home/fs/.local/lib/python3.6/site-packages/dhooks/__init__.py", line 1, in <module>
    from .client import Webhook
  File "/home/fs/.local/lib/python3.6/site-packages/dhooks/client.py", line 118
    URL_REGEX = r'^(?:https?://)?((canary|ptb)\.)?discordapp\.com/api/webhooks/' \
```
Id appreciate any help, thank you!

**Comment by dducted** [comment]
The webhook_url looks as follows:
`webhook_url = "https://discordapp.com/api/webhooks/656601084168503297/gF5nyCdCS6dnCQf0duyTBSKEnMOQUIozoQmzP30S2RFR0SAbCCEYngjJT6e2Oe3uYzi2"`

**Comment by DAzVise** [comment]
What version of dhooks are you using

**Comment by mischievousdev** [comment]
This issue is solved!

**Comment by Technetium1** [comment]
This should be fixed in https://github.com/kyb3r/dhooks/commit/cd9f9aea7168bf60b5774eeeb3e8cbc52900fddd
