### ISSUE TITLE
suggestion: give timestamps the same functionality as in discord.py

### ISSUE THREAD

**Issue by Hexiro** [kyb3r/dhooks#46]
in discord.py, you can pass an aware datetime object when creating and embed. With dhooks, the code only checks for the string "now" which gets filled with an unaware datetime object. While using "now" does decrease complexity slightly for new users, it increases confusion by not being the same as discord.py. if I'm misunderstanding how to pass a datetime object as a timestamp arg for an embed, please let me know, as my code isn't run locally and using another timezone is confusing.

**Comment by Looskie** [comment]
Yes pleaseeee!!!!

**Comment by Hexiro** [comment]
To you, or to anyone else reading this, you just need to convert the datetime object to a string. discord.py does this under the hood and does some other stuff to not clutter discord servers. if a maintainer is reading this, consider adding this to the documentation examples and/or add copy the lines that discord.py uses, as all of dhooks.Embed is basically discord.Embed anyway.

**Comment by Hexiro** [comment]
personally, this confused me from the line `Note: Embed objects from discord.py are also compatible with this library.`  in the README.md, as the code isn't the exact same.
